import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: "autogenerated", dirName: "." }, // Keeps your automatic doc structure
    {
      type: "link",
      label: "Docusaurus Basics",
      href: "https://adrianoruseler.github.io/site/docs/docusaurus/folder",
    },
  ],
};

export default sidebars;
