PRAGMA foreign_keys = ON;

--
-- Table structure for table DOMINIO_BANCAS
--

DROP TABLE IF EXISTS DOMINIO_BANCAS;
CREATE TABLE DOMINIO_BANCAS (
  ID INTEGER NOT NULL,
  NOME TEXT DEFAULT NULL,
  PRIMARY KEY (ID)
);

--
-- Table structure for table DOMINIO_DEVEDORES
--

DROP TABLE IF EXISTS DOMINIO_DEVEDORES;
CREATE TABLE DOMINIO_DEVEDORES (
  ID INTEGER NOT NULL,
  NOME TEXT DEFAULT NULL,
  PRIMARY KEY (ID)
);

--
-- Table structure for table DOCUMENTOS
--

DROP TABLE IF EXISTS DOCUMENTOS;
CREATE TABLE DOCUMENTOS (
  ID INTEGER NOT NULL,
  NOME TEXT NOT NULL,
  ID_DEVEDOR INTEGER NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT DOCUMENTOS_FK FOREIGN KEY (ID_DEVEDOR) REFERENCES DOMINIO_DEVEDORES (ID)
);
CREATE INDEX IF NOT EXISTS DOCUMENTOS_FK ON DOCUMENTOS (ID_DEVEDOR);

--
-- Table structure for table AGREGADOR_DOCUMENTOS
--

DROP TABLE IF EXISTS AGREGADOR_DOCUMENTOS;
CREATE TABLE AGREGADOR_DOCUMENTOS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_AGREGADOR TEXT NOT NULL,
  ID_DOCUMENTO INTEGER NOT NULL,
  DATA_LIMITE_ATUAL TEXT NOT NULL,
  CONSTRAINT AGREGADOR_DOCUMENTOS_FK FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTOS (ID)
);
CREATE INDEX IF NOT EXISTS AGREGADOR_DOCUMENTOS_FK ON AGREGADOR_DOCUMENTOS (ID_DOCUMENTO);

--
-- Table structure for table EQUIPES
--

DROP TABLE IF EXISTS EQUIPES;
CREATE TABLE EQUIPES (
  ID TEXT NOT NULL,
  TITULO TEXT NOT NULL,
  ATIVA INTEGER NOT NULL,
  ID_LIDER INTEGER NOT NULL,
  DATA_INICIO TEXT NOT NULL,
  DATA_FIM TEXT DEFAULT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT EQUIPES_LIDERES_FK FOREIGN KEY (ID_LIDER) REFERENCES PROFESSORES (ID)
);
CREATE INDEX IF NOT EXISTS EQUIPES_LIDERES_FK ON EQUIPES (ID_LIDER);

--
-- Table structure for table BANCAS_EQUIPES
--

DROP TABLE IF EXISTS BANCAS_EQUIPES;
CREATE TABLE BANCAS_EQUIPES (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_TIPO INTEGER NOT NULL,
  ID_EQUIPE TEXT NOT NULL,
  NOTA REAL DEFAULT NULL,
  DATA_APRESENTACAO TEXT DEFAULT NULL,
  HORA_APRESENTACAO TEXT DEFAULT NULL,
  DATA_INICIO TEXT NOT NULL,
  DATA_FIM TEXT DEFAULT NULL,
  CONSTRAINT BANCAS_EQUIPES_FK_1 FOREIGN KEY (ID_TIPO) REFERENCES DOMINIO_BANCAS (ID),
  CONSTRAINT BANCAS_EQUIPES_FK_2 FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPES (ID)
);
CREATE INDEX IF NOT EXISTS BANCAS_EQUIPES_FK_1 ON BANCAS_EQUIPES (ID_TIPO);
CREATE INDEX IF NOT EXISTS BANCAS_EQUIPES_FK_2 ON BANCAS_EQUIPES (ID_EQUIPE);

--
-- Table structure for table BANCAS_PROFESSORES
--

DROP TABLE IF EXISTS BANCAS_PROFESSORES;
CREATE TABLE BANCAS_PROFESSORES (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_BANCA INTEGER NOT NULL,
  ID_PROFESSOR INTEGER NOT NULL,
  CONSTRAINT BANCAS_PROFESSORES_FK1 FOREIGN KEY (ID_BANCA) REFERENCES BANCAS_EQUIPES (ID),
  CONSTRAINT BANCAS_PROFESSORES_FK2 FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSORES (ID)
);
CREATE INDEX IF NOT EXISTS BANCAS_PROFESSORES_FK1 ON BANCAS_PROFESSORES (ID_BANCA);
CREATE INDEX IF NOT EXISTS BANCAS_PROFESSORES_FK2 ON BANCAS_PROFESSORES (ID_PROFESSOR);

--
-- Table structure for table EQUIPES_ALUNOS
--

DROP TABLE IF EXISTS EQUIPES_ALUNOS;
CREATE TABLE EQUIPES_ALUNOS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_EQUIPE TEXT NOT NULL,
  ID_ALUNO INTEGER NOT NULL,
  DATA_INICIO TEXT NOT NULL,
  DATA_FIM TEXT DEFAULT NULL,
  CONSTRAINT EQUIPES_ALUNOS_FK1 FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPES (ID),
  CONSTRAINT EQUIPES_ALUNOS_FK2 FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS (ID)
);
CREATE INDEX IF NOT EXISTS EQUIPES_ALUNOS_FK1 ON EQUIPES_ALUNOS (ID_EQUIPE);
CREATE INDEX IF NOT EXISTS EQUIPES_ALUNOS_FK2 ON EQUIPES_ALUNOS (ID_ALUNO);

--
-- Table structure for table EQUIPES_DISCIPLINAS
--

DROP TABLE IF EXISTS EQUIPES_DISCIPLINAS;
CREATE TABLE EQUIPES_DISCIPLINAS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_EQUIPE TEXT NOT NULL,
  ID_DISCIPLINA TEXT NOT NULL,
  ID_TURMA TEXT NOT NULL,
  DATA_INICIO TEXT NOT NULL,
  DATA_FIM TEXT DEFAULT NULL,
  CONSTRAINT EQUIPES_DISCIPLINAS_FK1 FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPES (ID),
  CONSTRAINT EQUIPES_DISCIPLINAS_FK2 FOREIGN KEY (ID_DISCIPLINA) REFERENCES DOMINIO_DISCIPLINAS (ID)
);
CREATE INDEX IF NOT EXISTS EQUIPES_DISCIPLINAS_FK1 ON EQUIPES_DISCIPLINAS (ID_EQUIPE);
CREATE INDEX IF NOT EXISTS EQUIPES_DISCIPLINAS_FK2 ON EQUIPES_DISCIPLINAS (ID_DISCIPLINA);

--
-- Table structure for table EQUIPES_DOCUMENTOS
--

DROP TABLE IF EXISTS EQUIPES_DOCUMENTOS;
CREATE TABLE EQUIPES_DOCUMENTOS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_EQUIPE TEXT NOT NULL,
  ID_DOCUMENTO INTEGER NOT NULL,
  DATA_LIMITE TEXT NOT NULL,
  DATA TEXT DEFAULT NULL,
  FORCADO INTEGER NOT NULL,
  CONSTRAINT EQUIPES_DOCUMENTOS_FK1 FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPES (ID),
  CONSTRAINT EQUIPES_DOCUMENTOS_FK2 FOREIGN KEY (ID_DOCUMENTO) REFERENCES DOCUMENTOS (ID)
);
CREATE INDEX IF NOT EXISTS EQUIPES_DOCUMENTOS_FK1 ON EQUIPES_DOCUMENTOS (ID_EQUIPE);
CREATE INDEX IF NOT EXISTS EQUIPES_DOCUMENTOS_FK2 ON EQUIPES_DOCUMENTOS (ID_DOCUMENTO);

--
-- Table structure for table EQUIPES_ORIENTADORES
--

DROP TABLE IF EXISTS EQUIPES_ORIENTADORES;
CREATE TABLE EQUIPES_ORIENTADORES (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_EQUIPE TEXT NOT NULL,
  ID_ORIENTADOR INTEGER NOT NULL,
  ORIENTACAO INTEGER NOT NULL,
  DATA_INICIO TEXT NOT NULL,
  DATA_FIM TEXT DEFAULT NULL,
  CONSTRAINT EQUIPES_ORIENTADORES_FK_1 FOREIGN KEY (ID_EQUIPE) REFERENCES EQUIPES (ID),
  CONSTRAINT EQUIPES_ORIENTADORES_FK_2 FOREIGN KEY (ID_ORIENTADOR) REFERENCES PROFESSORES (ID)
);
CREATE INDEX IF NOT EXISTS EQUIPES_ORIENTADORES_FK_1 ON EQUIPES_ORIENTADORES (ID_EQUIPE);
CREATE INDEX IF NOT EXISTS EQUIPES_ORIENTADORES_FK_2 ON EQUIPES_ORIENTADORES (ID_ORIENTADOR);
