PRAGMA foreign_keys = ON;

--
-- Table structure for table ALUNOS
--

DROP TABLE IF EXISTS ALUNOS;
CREATE TABLE ALUNOS (
  ID INTEGER NOT NULL,
  NOME TEXT NOT NULL,
  EMAIL TEXT NOT NULL,
  DATA_INICIO TEXT NOT NULL,
  DATA_FIM TEXT DEFAULT NULL,
  PRIMARY KEY (ID)
);

--
-- Table structure for table PROFESSORES
--

DROP TABLE IF EXISTS PROFESSORES;
CREATE TABLE PROFESSORES (
  ID INTEGER NOT NULL,
  NOME TEXT NOT NULL,
  EMAIL TEXT DEFAULT NULL,
  EMAIL2 TEXT DEFAULT NULL,
  EFETIVO INTEGER NOT NULL,
  DATA_INICIO TEXT NOT NULL,
  DATA_FIM TEXT DEFAULT NULL,
  PRIMARY KEY (ID)
);

--
-- Table structure for table DOMINIO_DISCIPLINAS
--

DROP TABLE IF EXISTS DOMINIO_DISCIPLINAS;
CREATE TABLE DOMINIO_DISCIPLINAS (
  ID TEXT NOT NULL,
  ID_RESPONSAVEL INTEGER NOT NULL,
  ID_COORDENADOR INTEGER NOT NULL,
  ID_AGREGADOR TEXT NOT NULL,
  NOME TEXT NOT NULL,
  CURSO TEXT NOT NULL,
  SIGLA TEXT NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT DOMINIO_DISCIPLINAS_FK1 FOREIGN KEY (ID_RESPONSAVEL) REFERENCES PROFESSORES (ID),
  CONSTRAINT DOMINIO_DISCIPLINAS_FK2 FOREIGN KEY (ID_COORDENADOR) REFERENCES PROFESSORES (ID)
);
CREATE INDEX IF NOT EXISTS DOMINIO_DISCIPLINAS_FK1 ON DOMINIO_DISCIPLINAS (ID_RESPONSAVEL);
CREATE INDEX IF NOT EXISTS DOMINIO_DISCIPLINAS_FK2 ON DOMINIO_DISCIPLINAS (ID_COORDENADOR);

--
-- Table structure for table ALUNOS_DISCIPLINAS
--

DROP TABLE IF EXISTS ALUNOS_DISCIPLINAS;
CREATE TABLE ALUNOS_DISCIPLINAS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_ALUNO INTEGER NOT NULL,
  ID_DISCIPLINA TEXT NOT NULL,
  ID_TURMA TEXT NOT NULL,
  DATA_INICIO TEXT NOT NULL,
  DATA_FIM TEXT DEFAULT NULL,
  CONSTRAINT ALUNOS_DISCIPLINAS_FK1 FOREIGN KEY (ID_DISCIPLINA) REFERENCES DOMINIO_DISCIPLINAS (ID),
  CONSTRAINT ALUNOS_DISCIPLINAS_FK2 FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS (ID)
);
CREATE INDEX IF NOT EXISTS ALUNOS_DISCIPLINAS_FK1 ON ALUNOS_DISCIPLINAS (ID_DISCIPLINA);
CREATE INDEX IF NOT EXISTS ALUNOS_DISCIPLINAS_FK2 ON ALUNOS_DISCIPLINAS (ID_ALUNO);

--
-- Table structure for table GRUPOS
--

DROP TABLE IF EXISTS GRUPOS;
CREATE TABLE GRUPOS (
  ID INTEGER NOT NULL,
  NOME TEXT NOT NULL,
  ID_LIDER INTEGER NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT GRUPOS_FK1 FOREIGN KEY (ID_LIDER) REFERENCES PROFESSORES (ID)
);
CREATE INDEX IF NOT EXISTS GRUPOS_FK1 ON GRUPOS (ID_LIDER);

--
-- Table structure for table PROFESSORES_GRUPOS
--

DROP TABLE IF EXISTS PROFESSORES_GRUPOS;
CREATE TABLE PROFESSORES_GRUPOS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_PROFESSOR INTEGER NOT NULL,
  ID_GRUPO INTEGER NOT NULL,
  DATA_INICIO TEXT NOT NULL,
  DATA_FIM TEXT DEFAULT NULL,
  CONSTRAINT PROFESSORES_GRUPOS_FK1 FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSORES (ID),
  CONSTRAINT PROFESSORES_GRUPOS_FK2 FOREIGN KEY (ID_GRUPO) REFERENCES GRUPOS (ID)
);
CREATE INDEX IF NOT EXISTS PROFESSORES_GRUPOS_FK1 ON PROFESSORES_GRUPOS (ID_PROFESSOR);
CREATE INDEX IF NOT EXISTS PROFESSORES_GRUPOS_FK2 ON PROFESSORES_GRUPOS (ID_GRUPO);

--
-- Table structure for table PROFESSORES_INTERESSES
--

DROP TABLE IF EXISTS PROFESSORES_INTERESSES;
CREATE TABLE PROFESSORES_INTERESSES (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_PROFESSOR INTEGER NOT NULL,
  INTERESSE TEXT NOT NULL,
  CONSTRAINT PROFESSORES_INTERESSES_FK1 FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSORES (ID)
);
CREATE INDEX IF NOT EXISTS PROFESSORES_INTERESSES_FK1 ON PROFESSORES_INTERESSES (ID_PROFESSOR);

--
-- Table structure for table PROFESSORES_TEMAS
--

DROP TABLE IF EXISTS PROFESSORES_TEMAS;
CREATE TABLE PROFESSORES_TEMAS (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  ID_PROFESSOR INTEGER NOT NULL,
  TEMA TEXT NOT NULL,
  CONSTRAINT PROFESSORES_TEMAS_FK1 FOREIGN KEY (ID_PROFESSOR) REFERENCES PROFESSORES (ID)
);
CREATE INDEX IF NOT EXISTS PROFESSORES_TEMAS_FK1 ON PROFESSORES_TEMAS (ID_PROFESSOR);
